[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "churn_prediction"
version = "0.0.1"
description = "This project relates to DEPT's Data Science \u0026 AI Case Assignment. The goal is to develop a churn prediction model and take proactive measures delivering tailored email messaging using GenAI."
authors = [
  { name = "Mario Chavez" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = ">=3.10.0"


[tool.ruff]
line-length = 99
src = ["churn_prediction"]
include = ["pyproject.toml", "churn_prediction/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["churn_prediction"]
force-sort-within-sections = true

